Pretty
homegamesio/homegames-web pull request #5
Opened 2020-07-15 01:08 UTC by prosif

Update to use new squish stuff in https://github.com/homegamesio/squish/pull/3 and make https://github.com/homegamesio/homegames/pull/34 work

2020-08-09 19:31 UTC, YazeedLoonat requested changes
I think after the issues after the rebase in the squish file, we would need to make updates here as well

2020-08-09 19:31 UTC, YazeedLoonat commented on package.json
> -    "squishjs": "^0.4.2"
I think this version number needs to be up'ed

2020-08-09 19:31 UTC, YazeedLoonat commented on src/app.js
> +const divColor = Colors.HG_YELLOW;//BLACK;
```suggestion
const divColor = Colors.COLORS.HG_YELLOW;//BLACK;
```

2020-08-20 04:02 UTC, prosif commented
Updated to use the version of squish currently in PR: https://github.com/homegamesio/squish/pull/3

Likely still busted in some way, but I need to update https://github.com/homegamesio/homegames/pull/34 to make _that_ work with squishjs 0.5.0 and then update this package to do the same. Basically the goal is "make master work"

2020-08-29 17:39 UTC, prosif commented
Similar to https://github.com/homegamesio/homegames/pull/34, I'm going to merge this and do other cleanup/fixes in other PRs

2020-08-29 17:39 UTC, merged